FROM bitnami/spark:latest

USER root

RUN install_packages python3 python3-pip

RUN ln -sf /usr/bin/python3 /usr/local/bin/python && \
    ln -sf /usr/bin/pip3 /usr/local/bin/pip

RUN pip3 install --no-cache-dir kafka-python pandas

USER 1001