FROM bitnami/spark:latest

USER root

RUN install_packages python3 python3-pip

RUN ln -sf /usr/bin/python3 /usr/local/bin/python && \
    ln -sf /usr/bin/pip3 /usr/local/bin/pip

RUN pip3 install --no-cache-dir kafka-python pandas

# GCS connector: Spark/Hadoop classpath
ADD https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-latest.jar /opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar

# Service account JSON buraya mount edilecek
RUN mkdir -p /opt/gcp-credentials && \
    chown -R 1001:0 /opt/gcp-credentials /opt/bitnami/spark/jars

USER 1001