version: 2

models:
  - name: fct_machine_events
    description: "Aggregated machine events"

    columns:
      - name: machine_id
        tests:
          - not_null

      - name: event_type
        tests:
          - not_null

      - name: total_events
        tests:
          - not_null

      - name: error_events

      - name: first_event_time

      - name: last_event_time